// Identical question order and CNY thresholds to the original WAIC assessment.
export const internationalQuestions = {
 de: [
 ['Wie hoch sind die Anschaffungs- oder Ersatzkosten Ihrer wichtigsten Anlage?','Betrachten Sie eine Kernmaschine oder eine nicht ersetzbare Maschinengruppe. Alle Beträge sind in CNY.','Über 500.000 CNY oder importierte bzw. kundenspezifische Anlage','100.000–500.000 CNY','Unter 100.000 CNY und leicht ersetzbar'],
 ['Ist die Anlage ein Produktionsengpass oder Teil eines unverzichtbaren Prozesses?','Berücksichtigen Sie vor- und nachgelagerte Prozesse.','Ja, ihr Ausfall hält die gesamte Linie auf','Teilweise kritisch; Alternativen sind begrenzt','Nein, ausreichende Redundanz ist vorhanden'],
 ['Wie leicht sind Ersatzteile und Reparaturleistungen verfügbar?','Berücksichtigen Sie Lieferzeiten, Service und Ersatzmöglichkeiten.','Schwierig: mehr als ein Monat Vorlauf','Mit rechtzeitiger Vorbereitung verfügbar','Einfach: Unterstützung vor Ort ist schnell verfügbar'],
 ['Wie hoch ist der direkte Verlust bei einem ungeplanten Stillstand?','Schätzen Sie anhand von Stillstandsdauer, Produktionsmenge und Marge. Beträge in CNY.','Über 50.000 CNY','10.000–50.000 CNY','Unter 10.000 CNY'],
 ['Beeinträchtigt ein Stillstand Liefertermine oder Auftragszusagen?','Denken Sie an Verzögerungen, Vertragsstrafen, Beschwerden oder verlorene Aufträge.','Ja, Risiko von Vertragsstrafen, Beschwerden oder Auftragsverlusten','Möglicherweise, aber es gibt zeitlichen Spielraum','Geringe oder keine Auswirkungen auf Lieferungen'],
 ['Können Anlagenfehler Qualitäts-, Sicherheits- oder Umweltrisiken verursachen?','Berücksichtigen Sie Folgen über den Produktionsausfall hinaus.','Ja, möglicherweise schwerwiegende Qualitäts-, Sicherheits- oder Umweltvorfälle','Gewisse Qualitäts- oder betriebliche Risiken','Kaum zusätzliche Risiken'],
 ['Können Sie Betriebsdaten kritischer Anlagen zuverlässig erfassen?','Zum Beispiel Schwingungen, Temperatur, Strom, Druck, Drehzahl und Alarme.','Ja, Schnittstellen und wichtige Parameter sind zugänglich','Teilweise: zusätzliche Sensoren oder Schnittstellenarbeiten sind nötig','Überwiegend nicht: geschlossene Schnittstellen oder keine Datenausgabe'],
 ['Wie vollständig sind Betriebs-, Wartungs- und Fehleraufzeichnungen?','Historische Daten helfen bei der Einordnung und Überprüfung von Befunden.','Mehr als zwei Jahre weitgehend vollständige Aufzeichnungen','Einzelne Aufzeichnungen ohne einheitliche Struktur','Fast keine; überwiegend mündliche oder handschriftliche Angaben'],
 ['Lassen sich Daten einzelnen Maschinen, Betriebszuständen und Wartungsmaßnahmen zuordnen?','Nachvollziehbare Daten unterstützen Analyse und Überprüfung.','Ja, einheitliche Datendefinitionen und Anlagenverzeichnisse','Teilweise, mit manueller Bereinigung und Aufbereitung','Nein, Daten sind verteilt und schwer zuzuordnen'],
 ['Kann das Instandhaltungsteam Trends, Alarme und einfache Zustandsanalysen verstehen?','Mindestens eine Person sollte Alarme bewerten und nachverfolgen können.','Ja, das Team hat Analyse- oder Diagnoseerfahrung','Lernbereitschaft vorhanden, aber wenig Erfahrung','Derzeit fehlt eine zuständige Person mit diesen Fähigkeiten'],
 ['Wie offen ist das Team für datenbasierte Instandhaltung?','Erfahrung und Daten sollten sich gegenseitig ergänzen.','Sehr offen für datenbasierte Entscheidungen','Unterschiedliche Sichtweisen; Schulung und Pilotprojekt würden helfen','Deutliche Vorbehalte; Reparatur erst nach dem Ausfall ist üblich'],
 ['Können Produktion, Einkauf und Führung gemeinsam auf Alarme reagieren?','Denken Sie an Wartungsfenster, Ersatzteile und Zuständigkeiten.','Ja, die Zusammenarbeit funktioniert gut','Einige Hürden, aber Unterstützung durch die Führung','Schwierig: Frühwarnungen führen selten zu Maßnahmen in der Produktion']
 ],
 ar: [
 ['ما تكلفة شراء أو استبدال أهم معداتك؟','قيّم آلة أساسية واحدة أو مجموعة لا يسهل استبدالها. جميع المبالغ باليوان الصيني CNY.','أكثر من 500,000 يوان، أو معدات مستوردة أو مصممة خصيصًا','من 100,000 إلى 500,000 يوان','أقل من 100,000 يوان ويسهل استبدالها'],
 ['هل تمثل هذه المعدة نقطة اختناق في الإنتاج أو جزءًا أساسيًا من العملية؟','ضع في الاعتبار أثر التوقف على المراحل السابقة واللاحقة.','نعم، تعطلها يوقف الخط بالكامل','مهمة جزئيًا مع بدائل محدودة','لا، توجد قدرة احتياطية كافية'],
 ['ما مدى سهولة الحصول على قطع الغيار وخدمات الإصلاح؟','ضع في الاعتبار مهلة التوريد واستجابة الخدمة وتوفر البدائل.','صعب: يتطلب أكثر من شهر','متوسط: يحتاج إلى تحضير مسبق','سهل: يتوفر دعم محلي سريع'],
 ['ما الخسارة المباشرة المعتادة لكل توقف غير مخطط؟','قدّرها حسب مدة التوقف وحجم الإنتاج وهامش الربح. المبالغ باليوان الصيني CNY.','أكثر من 50,000 يوان','من 10,000 إلى 50,000 يوان','أقل من 10,000 يوان'],
 ['هل يؤثر التوقف على التسليم للعملاء أو الالتزام بالطلبات؟','فكّر في التأخير والغرامات والشكاوى وخسارة الطلبات.','نعم، مع احتمال غرامات أو شكاوى أو خسارة طلبات','قد يؤثر، لكن يمكن استيعاب بعض التأخير','أثر ضئيل أو معدوم على التسليم'],
 ['هل قد تؤدي أعطال المعدات إلى مخاطر على الجودة أو السلامة أو البيئة؟','ضع في الاعتبار الآثار التي تتجاوز خسارة الإنتاج.','نعم، قد تسبب مشكلات جسيمة في الجودة أو السلامة أو البيئة','توجد بعض المخاطر على الجودة أو الموقع','مخاطر إضافية محدودة جدًا'],
 ['هل يمكنك جمع بيانات تشغيل المعدات الحرجة بصورة موثوقة؟','مثل الاهتزاز والحرارة والتيار والضغط والسرعة والإنذارات.','نعم، الواجهات والبيانات الأساسية متاحة','جزئيًا: نحتاج إلى مستشعرات أو أعمال ربط إضافية','غالبًا لا: الواجهات مغلقة أو لا توجد مخرجات بيانات'],
 ['ما مدى اكتمال سجلات التشغيل والصيانة والأعطال؟','تساعد السجلات السابقة على فهم السياق والتحقق من النتائج.','سجلات مكتملة نسبيًا لأكثر من عامين','سجلات متفرقة دون تنظيم موحد','لا توجد تقريبًا؛ المعلومات شفهية أو مكتوبة يدويًا'],
 ['هل يمكن ربط البيانات بمعدات محددة وظروف التشغيل وإجراءات الصيانة؟','تدعم البيانات القابلة للتتبع التحليل والتحقق.','نعم، تعريفات البيانات وسجلات المعدات متسقة','جزئيًا، مع تنظيف البيانات وإعدادها يدويًا','لا، البيانات متفرقة ويصعب تتبعها'],
 ['هل يستطيع فريق الصيانة تفسير الاتجاهات والإنذارات وتحليل الحالة الأساسي؟','ينبغي وجود شخص واحد على الأقل يستطيع تفسير الإنذارات ومتابعتها.','نعم، لدى الفريق خبرة في التحليل أو التشخيص','يوجد استعداد للتعلم لكن الخبرة محدودة','لا يوجد حاليًا شخص يمتلك هذه القدرة أو يتولى مسؤوليتها'],
 ['ما مدى تقبل فريق الموقع للصيانة المبنية على البيانات؟','ينبغي أن تكمل الخبرة والبيانات بعضهما بعضًا.','تقبل كبير لاستخدام البيانات في اتخاذ القرار','آراء متباينة؛ قد يفيد التدريب والتطبيق التجريبي','مقاومة واضحة؛ المعتاد هو الإصلاح بعد العطل'],
 ['هل تستطيع فرق الإنتاج والمشتريات والإدارة التنسيق للاستجابة للإنذارات؟','فكّر في نوافذ الصيانة وقطع الغيار ومسؤولية المتابعة.','نعم، التنسيق بين الفرق جيد','توجد بعض العوائق لكن الإدارة داعمة','صعب: نادرًا ما تتخذ فرق الإنتاج إجراءات بناءً على الإنذار المبكر']
 ]
};
export const internationalResults: Record<'de'|'ar',Record<string,[string,string]>> = {
 de:{immediate:['Gezieltes Pilotprojekt priorisieren','Beginnen Sie mit einer oder zwei kritischen Maschinen. Legen Sie Datenzugang und Abnahmekriterien fest und überprüfen Sie den Ablauf von Alarm, Kontrolle und Instandhaltung.'],pilot:['Mit einem kleinen Pilotprojekt beginnen','Wählen Sie eine kritische Maschine, schließen Sie Daten- oder Abstimmungslücken und prüfen Sie die Ergebnisse anhand von Betriebs- und Wartungsrückmeldungen, bevor Sie erweitern.'],postpone:['Zuerst die Grundlagen schaffen','Ordnen Sie Anlagen- und Fehleraufzeichnungen, klären Sie die Datenerfassung und benennen Sie eine verantwortliche Person vor Ort. Bewerten Sie danach die Investition erneut.'],notNow:['Derzeit keine vorrangige Maßnahme','Priorisieren Sie für die bewertete Anlage Inspektionen, vorbeugende Wartung und Ersatzteile. Bewerten Sie die Situation bei geänderten Anlagen- oder Betriebsbedingungen neu.'],pending:['Weitere Informationen erforderlich','Klären Sie die unbekannten Punkte mit den Anlagenverantwortlichen, bevor Sie über das weitere Vorgehen entscheiden.']},
 ar:{immediate:['أعطِ الأولوية لتطبيق تجريبي محدد','ابدأ بآلة أو آلتين حرجتين. اتفق على الوصول إلى البيانات ومعايير القبول، ثم تحقق من مسار الإنذار والفحص والصيانة.'],pilot:['ابدأ بتطبيق تجريبي صغير','اختر آلة حرجة واحدة، وعالج الفجوات في البيانات أو التنسيق، ثم تحقق من النتائج عبر ملاحظات التشغيل والصيانة قبل التوسع.'],postpone:['جهّز الأساس أولًا','نظّم سجلات المعدات والأعطال، وحدد طرق جمع البيانات ومسؤولًا في الموقع، ثم أعد تقييم الاستثمار.'],notNow:['ليست أولوية في المرحلة الحالية','بالنسبة للمعدات التي قيّمتها، أعطِ الأولوية للفحص والصيانة الوقائية وقطع الغيار. أعد التقييم عند تغير المعدات أو ظروف التشغيل.'],pending:['نحتاج إلى معلومات إضافية','راجع البنود غير المعروفة مع مسؤول المعدات قبل تحديد الخطوة التالية.']}
};
// Keys are the existing English UI strings, keeping the original three languages intact.
export const assessmentInternational:Record<string,[string,string]> = {
 'Equipment value':['Anlagenwert','قيمة المعدات'],
 'Downtime impact':['Stillstandsfolgen','أثر التوقف'],
 'Data readiness':['Datenbasis','جاهزية البيانات'],
 'Team readiness':['Teamkompetenz','جاهزية الفريق'],
 'Next steps':['Nächste Schritte','الخطوات التالية'],
 'WeChat':['WeChat','وي تشات'], 'Phone':['Telefon','الهاتف'], 'Email':['E-Mail','البريد الإلكتروني'],
 'Please enter valid contact details.':['Bitte geben Sie gültige Kontaktdaten ein.','يرجى إدخال وسيلة تواصل صحيحة.'],
 'Please agree to be contacted about this assessment.':['Bitte stimmen Sie der Kontaktaufnahme zu dieser Bewertung zu.','يرجى الموافقة على التواصل معك بشأن هذا التقييم.'],
 'Too many submissions. Please try later or call us.':['Zu viele Übermittlungen. Bitte versuchen Sie es später erneut oder rufen Sie uns an.','عدد الإرسالات كبير. يرجى المحاولة لاحقًا أو الاتصال بنا.'],
 'Submission could not be confirmed. Your answers are still here. Retry or call us; retrying will not create a duplicate.':['Die Übermittlung konnte nicht bestätigt werden. Ihre Antworten bleiben hier erhalten. Versuchen Sie es erneut oder rufen Sie uns an. Ein erneuter Versuch erzeugt keinen doppelten Eintrag.','تعذر تأكيد الإرسال. إجاباتك ما زالت هنا. أعد المحاولة أو اتصل بنا؛ لن تؤدي إعادة المحاولة إلى إنشاء سجل مكرر.'],
 'Back to site':['Zur Website','العودة إلى الموقع'],
 'Where should your equipment journey start?':['Wo beginnt der nächste Schritt für Ihre Anlagen?','من أين تبدأ مع معداتك؟'],
 'Not one more thing to manage. One less thing to do.':['Nicht noch mehr verwalten. Eine Aufgabe weniger.','ليس عبئًا جديدًا تديره، بل مهمة أقل تنجزها.'],
 '12 selections':['12 Auswahlfragen','12 سؤالًا اختياريًا'],
 'No long forms':['Keine langen Formulare','دون نماذج مطولة'],
 'Results before contact':['Ergebnis vor Kontaktaufnahme','النتيجة قبل التواصل'],
 'This checks project suitability, not equipment health or failure risk.':['Diese Selbstbewertung prüft die Projekteignung, nicht den Anlagenzustand oder das Ausfallrisiko.','هذا تقييم لملاءمة المشروع، وليس تشخيصًا لصحة المعدات أو مخاطر الأعطال.'],
 'Application assessment':['Anwendungsbewertung','تقييم التطبيق'], 'Progress':['Fortschritt','التقدم'],
 'Answer for the same machine or group throughout. All amounts are in CNY. Select “Not sure” where needed.':['Beziehen Sie alle Antworten auf dieselbe Maschine oder Gruppe. Alle Beträge sind in CNY. Wählen Sie bei Bedarf „Unklar“.','أجب عن المعدة نفسها أو المجموعة نفسها في جميع الأسئلة. المبالغ باليوان الصيني CNY. اختر «غير متأكد» عند الحاجة.'],
 'Select an option':['Bitte auswählen','اختر إجابة'], 'Not sure':['Unklar','غير متأكد'], 'Back':['Zurück','السابق'],
 'See my results':['Ergebnis anzeigen','عرض نتيجتي'], 'Next':['Weiter','التالي'],
 'Your initial assessment':['Ihre erste Einschätzung','تقييمك الأولي'], 'Start here':['Hier beginnen','ابدأ من هنا'],
 'Unknown items are not scored as zero. Clarify them before deciding how to proceed.':['Unbekannte Angaben werden nicht mit null bewertet. Klären Sie diese, bevor Sie das weitere Vorgehen festlegen.','لا تُحتسب الإجابات غير المعروفة بصفر. استكمل المعلومات قبل تحديد الخطوة التالية.'],
 'Quality, safety and environmental impacts require a separate site risk review. This assessment does not replace protective measures.':['Qualitäts-, Sicherheits- und Umweltauswirkungen erfordern eine gesonderte Risikoprüfung vor Ort. Diese Bewertung ersetzt keine Schutzmaßnahmen.','تتطلب آثار الجودة والسلامة والبيئة مراجعة مستقلة للمخاطر في الموقع. لا يحل هذا التقييم محل إجراءات الحماية.'],
 'Unknown':['Noch offen','غير مكتمل'], 'How is this assessed?':['Wie erfolgt die Bewertung?','كيف يتم التقييم؟'],
 'Each dimension has three questions worth 0, 1 or 2 points. Scores of 0–2 are low, 3–4 medium and 5–6 high. High value and impact with at least medium data and team readiness prioritize a pilot. High value or impact suggests a small pilot; low value and impact are not a priority. Other combinations depend on readiness. The dimensions are not combined into a percentage.':['Jede Dimension umfasst drei Fragen mit 0, 1 oder 2 Punkten. 0–2 Punkte gelten als niedrig, 3–4 als mittel und 5–6 als hoch. Hoher Anlagenwert und hohe Stillstandsfolgen bei mindestens mittlerer Daten- und Teamreife sprechen für ein priorisiertes Pilotprojekt. Hoher Wert oder hohe Auswirkungen sprechen für einen kleinen Pilotversuch; sind beide niedrig, besteht keine Priorität. Andere Kombinationen richten sich nach der Umsetzungsreife. Die Dimensionen werden nicht zu einem Prozentwert zusammengefasst.','يتضمن كل بُعد ثلاثة أسئلة، لكل منها 0 أو 1 أو 2 نقطة. مجموع 0–2 منخفض، و3–4 متوسط، و5–6 مرتفع. إذا ارتفعت القيمة والأثر وكانت جاهزية البيانات والفريق متوسطة على الأقل، يُعطى التطبيق التجريبي الأولوية. ارتفاع القيمة أو الأثر يدعم تجربة صغيرة، وانخفاضهما معًا يعني أولوية أقل. تعتمد الحالات الأخرى على الجاهزية. لا تُدمج الأبعاد في نسبة مئوية إجمالية.'],
 'Turn this assessment into a useful conversation':['Aus der Bewertung wird ein konkretes Gespräch','حوّل التقييم إلى حوار مفيد'],
 'One contact method is enough. Your answers will be included.':['Eine Kontaktmöglichkeit genügt. Ihre Antworten werden mitübermittelt.','وسيلة تواصل واحدة تكفي. ستُرفق إجاباتك معها.'],
 'Contact via':['Kontaktweg','وسيلة التواصل'],
 'WeChat ID or linked phone':['WeChat-ID oder verknüpfte Telefonnummer','معرّف وي تشات أو الهاتف المرتبط به'],
 'I agree that LinkedTi may store my assessment and contact details and contact me about this application.':['Ich bin damit einverstanden, dass LinkedTi meine Bewertung und Kontaktdaten speichert und mich zu dieser Anwendung kontaktiert.','أوافق على أن تحفظ LinkedTi تقييمي وبيانات التواصل وأن تتواصل معي بشأن هذا التطبيق.'],
 'How we use your information':['So verwenden wir Ihre Angaben','كيف نستخدم معلوماتك'],
 'Anhui LinkedTi uses this information for application review and sales follow-up. It is stored by our website and sent to responsible staff through business email. Contact sales@linkedti.com to request access, correction or deletion.':['Anhui LinkedTi verwendet diese Angaben zur Anwendungsprüfung und für die vertriebliche Kontaktaufnahme. Sie werden im Website-System gespeichert und per geschäftlicher E-Mail an zuständige Mitarbeitende übermittelt. Für Auskunft, Berichtigung oder Löschung wenden Sie sich an sales@linkedti.com.','تستخدم Anhui LinkedTi هذه المعلومات لمراجعة التطبيق والمتابعة التجارية. تُحفظ في نظام الموقع وتُرسل إلى الموظفين المسؤولين عبر البريد المهني. لطلب الاطلاع أو التصحيح أو الحذف، تواصل عبر sales@linkedti.com.'],
 'Submitting…':['Wird gesendet…','جارٍ الإرسال…'], 'Submit and contact me':['Absenden und Kontakt anfordern','أرسل التقييم وتواصل معي'],
 'Assessment received':['Bewertung erhalten','تم استلام التقييم'],
 'Your assessment and contact details have been saved. We will follow up using your chosen method. No separate email is needed.':['Ihre Bewertung und Kontaktdaten wurden gespeichert. Wir melden uns über den gewählten Kontaktweg. Eine separate E-Mail ist nicht nötig.','تم حفظ تقييمك وبيانات التواصل. سنتواصل معك بالطريقة التي اخترتها، ولا تحتاج إلى إرسال بريد منفصل.'],
 'Reference':['Referenz','رقم المرجع'], 'Edit my answers':['Antworten bearbeiten','تعديل إجاباتي']
};
