export const internationalContent = {
 de: {
  nav:['Produkte','Anwendungen','Über uns'], talk:'Anwendung bewerten', skip:'Zum Inhalt',
  eyebrow:'ZUSTANDSÜBERWACHUNG & VORAUSSCHAUENDE INSTANDHALTUNG',
  promise:['Nicht noch mehr verwalten.','Eine Aufgabe weniger.'],
  intro:'Wir integrieren die Überwachung des Maschinenzustands in Ihre bestehende Automatisierung. Physikalisches Anlagenwissen und KI unterstützen die Früherkennung und Ursachenanalyse – für eine planbare Instandhaltung.',
  explore:'Produkte entdecken', productsTitle:'Vom Messwert zur gezielten Maßnahme',
  productsIntro:'Sensorik, Gateways, Diagnosesoftware und KI lassen sich passend zu Ihrer Anlage kombinieren. Beginnen Sie mit kritischen Maschinen und erweitern Sie die Lösung nach Bedarf.',
  products:[
   ['Aura','Industriesensoren','Erfassen Temperatur, Schwingungen und Strom als Grundlage für die Trendbeobachtung und Fehleranalyse.','Messpunkte und Messgrößen werden auf Maschine, Betriebsbedingungen und Diagnoseziel abgestimmt.'],
   ['Conflux','Industriegateways','Verbinden Sensoren mit der vorhandenen Automatisierung, führen konfigurierte lokale Logik aus und stellen Zustandsdaten sowie Alarme für SPS und Leitsysteme bereit.','Die Integration richtet sich nach den verfügbaren Schnittstellen und der Steuerungsarchitektur vor Ort.'],
   ['Euda','Software für Anlagenzustand und Instandhaltung','Verknüpft Zustandsdaten, Trendanalysen und Diagnoseregeln mit Arbeitsaufträgen und Wartungsaufzeichnungen.','Von der Alarmbewertung bis zur Überprüfung nach der Instandsetzung bleiben Entscheidungen nachvollziehbar.'],
   ['Agent','KI für die industrielle Instandhaltung','Kombiniert physikalisches Anlagenwissen mit großen Sprachmodellen und verbindet Analyse, Prüfung vor Ort, Berichte und Wissensaufbau.','Der geschlossene Arbeitsablauf ist bereits umgesetzt und wird schrittweise weiterentwickelt. Befunde werden vor Ort überprüft.']
  ],
  integrationTitle:'Teil Ihrer Automatisierung',
  integrationIntro:'Zusätzliche Erkenntnisse sollen den Betrieb entlasten. Deshalb stellen wir Maschinenzustände und Diagnosealarme innerhalb bestehender SPS- und Leitsystemumgebungen bereit.',
  integrations:[['Siemens SPS / DCS','Integration von Zustandsdaten und Alarmen in vorhandene Steuerungs- und Leitsysteme.'],['Phoenix Contact PLCnext','Entwicklungsintegration mit PLCnext für die Verbindung von Automatisierung und Zustandsanalyse.'],['Klare Aufgabenverteilung','Eigene Endgeräte führen konfigurierte lokale Logik aus. Diagnose und Instandhaltungsabläufe ergänzen die vorhandene Produktionssteuerung.']],
  workflowTitle:'Aus Daten wird nutzbares Wissen', workflow:['Erfassen','Analysieren','Diagnostizieren','Vor Ort prüfen','Berichten','Wissen sichern'],
  workflowText:'Rückmeldungen aus der Instandhaltung machen Befunde überprüfbar und dokumentieren Erfahrungen für künftige Entscheidungen. So wächst ein nachvollziehbarer Daten- und Wissensbestand.',
  softwareTitle:'Die Anlage im Blick. Den nächsten Schritt im Fokus.', softwareText:'Euda unterstützt die Übersicht über Maschinenzustände, die Untersuchung von Auffälligkeiten und die Dokumentation von Maßnahmen.', softwareNote:'Abbildungen zeigen die chinesische Softwareoberfläche. Verfügbare Oberflächensprachen und Projektumfang stimmen wir gemeinsam ab.',
  applicationsTitle:'Kritische Anlagen. Konkrete Ansatzpunkte.', applicationsIntro:'Wir beginnen beim Ausfallrisiko und beim Arbeitsalltag Ihrer Instandhaltung. Ein realer Anwendungsfall aus einem Stahlwerk zeigt den Ansatz; die weiteren Karten beschreiben mögliche Anwendungen.',
  actual:'Praxisbeispiel · Stahlwerk', steelTitle:'Lagerschaden am Rollgang frühzeitig erkannt',
  steel:'Am Rollgang eines Walzwerks ergänzten Sensoren, Gateways und Software die bisherigen Kontrollgänge und einfachen Grenzwertalarme. Auffällige Schwingungen deuteten auf einen Lagerschaden hin, obwohl vor Ort noch keine deutlichen Anzeichen erkennbar waren. Bei einer ohnehin geplanten Revision bestätigte die Demontage Schäden an den Wälzkörpern. Das Lager wurde ersetzt. Die Zustandsanalyse half, Ersatzteile und Maßnahmen früher vorzubereiten.',
  steelNote:'Dieser Einsatz ergänzte das bestehende SPS-System. Ein KI-Agent war nicht Teil des Projekts.',
  industries:[
   ['Rechenzentren','Kühlung und Versorgung','Pumpen, Lüfter und weitere rotierende Hilfsaggregate überwachen, um Auffälligkeiten in der Kühl- und Versorgungsinfrastruktur zu untersuchen.'],
   ['Halbleiterfertigung','Versorgungsanlagen im Reinraumumfeld','Zustandsdaten von Pumpen, Lüftern und Versorgungseinrichtungen nutzen, um Wartungsbedarf mit den Anforderungen des Produktionsbetriebs abzustimmen.'],
   ['Chemische Industrie','Kontinuierliche Prozesse','Schwingungs- und Temperaturtrends an Pumpen und anderen rotierenden Maschinen beobachten und Befunde mit Betriebsbedingungen abgleichen.'],
   ['Flughäfen','Technische Infrastruktur','Antriebe von Gepäckförderanlagen und Lüftungstechnik überwachen, damit Kontrollen und Wartungsfenster gezielter vorbereitet werden können.'],
   ['Tabakindustrie','Produktions- und Fördertechnik','Zustandsänderungen an Antrieben und Transportanlagen erkennen und geplante Instandhaltung mit der Produktion koordinieren.'],
   ['Werften','Portalkräne','Antriebe, Getriebe und Lager von Portalkränen überwachen. Zustandsdiagnostik ergänzt die vorgeschriebenen Prüfungen und Schutzfunktionen.'],
   ['Kupferhütten','Aggregate im Dauerbetrieb','Lüfter, Pumpen und weitere rotierende Aggregate anhand ihrer Betriebszustände bewerten und Ersatzteilplanung unterstützen.'],
   ['Energiespeicher','Kühl- und Hilfssysteme','Pumpen und Lüfter der Kühlung überwachen. Der Schwerpunkt liegt auf mechanischen Hilfsaggregaten, nicht auf der Bewertung des Batteriezustands.'],
   ['Biopharmazeutische Produktion','Technische Versorgung','Pumpen, Lüfter und Hilfsaggregate überwachen und nachvollziehbare Wartungsaufzeichnungen unterstützen. Prozessfreigaben und Validierungen bleiben eigenständige Aufgaben.']
  ],
  exampleLabel:'Anwendungsszenario', aboutTitle:'Verbindungen, die Instandhaltung erleichtern.',
  aboutIntro:'Anhui LinkedTi Intelligent Technology Co., Ltd. (安徽交泰智能技术有限公司) entwickelt Hardware, Software und Diagnosealgorithmen für die intelligente Instandhaltung industrieller Anlagen. Wir arbeiten mit Anlagenbetreibern, Integrationspartnern und Maschinenherstellern zusammen.',
  storyTitle:'Was „交泰“ und LinkedTi bedeuten',
  story:['„交泰“ (Jiaotai) geht auf das Hexagramm Tai im chinesischen Buch der Wandlungen, dem I Ging, zurück: Himmel und Erde stehen in Verbindung und ermöglichen gemeinsames Gedeihen. Auch die Halle Jiaotai in der Verbotenen Stadt in Peking trägt diesen Namen. Für uns steht er für die Verbindung von Anlagen, Informationen und Menschen.',
  'Der Name LinkedTi wurde durch die Idee der Vernetzung bei LinkedIn inspiriert. Unser Fokus liegt auf der Verbindung industrieller Anlagen. „Linked“ steht für Vernetzung, „Ti“ ist das chemische Symbol für Titan und verkörpert unseren Anspruch an Qualität, Beständigkeit und zuverlässige Leistung.'],
  identityTitle:'Ein weiterentwickeltes Zeichen. Dasselbe Unternehmen.', identityText:'Wir haben unser Logo weiterentwickelt. Ältere Unterlagen können weiterhin das bisherige Zeichen tragen: Beide Logos stehen für dieselbe 安徽交泰智能技术有限公司 und die Marke LinkedTi. Die neue Gestaltung führt die Identität des Unternehmens fort.', oldLogo:'Bisheriges Logo',newLogo:'Aktuelles Logo',
  contactTitle:'Wo lohnt sich der erste Schritt?', contactText:'Beantworten Sie zwölf Auswahlfragen zu Anlagenwert, Stillstandsfolgen, Daten und Team. Sie sehen Ihre Einschätzung, bevor Sie eine Kontaktmöglichkeit hinterlassen.',
  address:'Gebäude R, Hongbaoshi, High-Tech-Zone, Hefei, Anhui, China', footer:'Zustandsüberwachung · Diagnose · Vorausschauende Instandhaltung', home:'Startseite'
 },
 ar: {
  nav:['المنتجات','التطبيقات','عن الشركة'],talk:'قيّم تطبيقك',skip:'انتقل إلى المحتوى',
  eyebrow:'مراقبة حالة المعدات والصيانة التنبؤية',
  promise:['ليس عبئًا جديدًا تديره،','بل مهمة أقل تنجزها.'],
  intro:'ندمج مراقبة حالة المعدات في أنظمة الأتمتة الموجودة لديك. نجمع بين فهم آليات عمل المعدات والذكاء الاصطناعي لدعم الاكتشاف المبكر للأعطال وتحليل أسبابها، وتحويل الصيانة إلى عمل يمكن التخطيط له.',
  explore:'اكتشف المنتجات',productsTitle:'من القياس إلى الإجراء المناسب',
  productsIntro:'يمكن الجمع بين المستشعرات والبوابات وبرامج التشخيص والذكاء الاصطناعي بما يناسب معداتك. ابدأ بالمعدات الحرجة، ثم وسّع نطاق التطبيق حسب الحاجة.',
  products:[
   ['Aura','مستشعرات صناعية','تجمع بيانات الحرارة والاهتزاز والتيار لدعم متابعة الاتجاهات وتحليل الأعطال.','تُحدد نقاط القياس والمتغيرات وفقًا للمعدة وظروف تشغيلها وهدف التشخيص.'],
   ['Conflux','بوابات صناعية','تربط المستشعرات بأنظمة الأتمتة الحالية، وتنفذ منطقًا محليًا وفق الإعدادات، وتوفر بيانات الحالة والإنذارات لأنظمة PLC وDCS.','يتحدد نطاق الربط حسب الواجهات المتاحة وبنية التحكم في الموقع.'],
   ['Euda','برنامج صحة المعدات والصيانة','يربط بيانات الحالة وتحليل الاتجاهات وقواعد التشخيص بأوامر العمل وسجلات الصيانة.','يحافظ على إمكانية تتبع القرارات، من تقييم الإنذار إلى التحقق بعد الإصلاح.'],
   ['Agent','وكيل ذكاء اصطناعي للصيانة الصناعية','يجمع بين فهم آليات المعدات والنماذج اللغوية الكبيرة لربط التحليل والتحقق الميداني والتقارير وتراكم المعرفة.','تعمل دورة المتابعة المتكاملة حاليًا وتُطوّر تدريجيًا، مع التحقق من نتائج التشخيص في الموقع.']
  ],
  integrationTitle:'جزء من منظومة الأتمتة لديك',integrationIntro:'ينبغي أن تقلل المعلومات الإضافية عبء التشغيل. لذلك نوفر حالات المعدات وإنذارات التشخيص ضمن بيئات التحكم والإشراف القائمة.',
  integrations:[['Siemens PLC / DCS','دمج بيانات الحالة والإنذارات مع أنظمة التحكم والإشراف الموجودة.'],['Phoenix Contact PLCnext','تكامل تطويري مع PLCnext لربط الأتمتة بتحليل حالة المعدات.'],['توزيع واضح للمهام','تنفذ وحداتنا الطرفية منطقًا محليًا وفق الإعدادات. ويكمل التشخيص وإجراءات الصيانة منظومة التحكم في الإنتاج.']],
  workflowTitle:'من البيانات إلى معرفة قابلة للاستخدام',workflow:['جمع البيانات','التحليل','التشخيص','التحقق الميداني','إعداد التقارير','حفظ المعرفة'],
  workflowText:'تتيح ملاحظات فرق الصيانة التحقق من نتائج التشخيص وتوثيق الخبرات للقرارات اللاحقة. وهكذا تتراكم بيانات ومعرفة يمكن تتبعها وإعادة استخدامها.',
  softwareTitle:'رؤية أوضح للمعدات وللخطوة التالية',softwareText:'يدعم Euda استعراض حالة المعدات، وفحص المؤشرات غير الطبيعية، وتوثيق الإجراءات المتخذة.',softwareNote:'تُظهر الصور واجهة البرنامج باللغة الصينية. يمكن الاتفاق على لغات الواجهة المتاحة ونطاق المشروع أثناء التواصل.',
  applicationsTitle:'معدات حرجة وفرص تطبيق محددة',applicationsIntro:'نبدأ من أثر الأعطال وطبيعة عمل فريق الصيانة. توضح حالة حقيقية في مصنع للصلب هذا النهج، بينما تعرض البطاقات الأخرى سيناريوهات تطبيق محتملة.',
  actual:'حالة تطبيق فعلية · مصنع صلب',steelTitle:'اكتشاف مبكر لتلف محمل في ناقل درفلة',
  steel:'في ناقل بكرات بمصنع درفلة، أضفنا مستشعرات وبوابات وبرنامجًا إلى الجولات التفقدية والإنذارات البسيطة القائمة على الحدود. أشارت اهتزازات غير طبيعية إلى تلف محمل، رغم عدم ظهور علامات واضحة عند الفحص الميداني. وأثناء توقف صيانة مخطط له، أكد فك المحمل وجود آثار تلف في عناصر التدحرج، فتم استبداله. ساعد تحليل الحالة على الاستعداد المبكر بقطع الغيار وإجراءات الصيانة.',
  steelNote:'كان هذا التطبيق مكمّلًا لنظام PLC الموجود، ولم يُستخدم فيه وكيل ذكاء اصطناعي.',
  industries:[
   ['مراكز البيانات','التبريد والمرافق المساندة','مراقبة المضخات والمراوح والمعدات الدوارة المساندة لدراسة المؤشرات غير الطبيعية في منظومات التبريد والمرافق.'],
   ['مصانع أشباه الموصلات','مرافق بيئات الغرف النظيفة','استخدام بيانات حالة المضخات والمراوح ومعدات المرافق لتنسيق احتياجات الصيانة مع متطلبات الإنتاج.'],
   ['الصناعات الكيميائية','العمليات المستمرة','متابعة اتجاهات الاهتزاز والحرارة في المضخات والمعدات الدوارة وربط نتائج التشخيص بظروف التشغيل.'],
   ['المطارات','البنية التحتية التشغيلية','مراقبة محركات أنظمة نقل الأمتعة ومعدات التهوية لدعم التحضير للفحص ونوافذ الصيانة.'],
   ['صناعة التبغ','معدات الإنتاج والنقل','رصد تغيرات حالة المحركات وأنظمة النقل وتنسيق الصيانة المخططة مع الإنتاج.'],
   ['أحواض بناء السفن','الرافعات الجسرية البوابية','مراقبة المحركات وعلب التروس والمحامل في الرافعات البوابية. ويكمل تشخيص الحالة الفحوص الإلزامية ووظائف الحماية.'],
   ['صهر النحاس','معدات التشغيل المستمر','تقييم المراوح والمضخات والمعدات الدوارة وفق ظروف تشغيلها، ودعم التخطيط لقطع الغيار.'],
   ['تخزين الطاقة','أنظمة التبريد والأنظمة المساندة','مراقبة مضخات التبريد ومراوحه. ينصب التركيز على المعدات الميكانيكية المساندة، وليس تقييم صحة البطاريات.'],
   ['الصناعات الدوائية الحيوية','المرافق الفنية','مراقبة المضخات والمراوح والمعدات المساندة ودعم سجلات صيانة قابلة للتتبع. تظل الموافقات والتحقق من صلاحية العمليات مهام مستقلة.']
  ],exampleLabel:'سيناريو تطبيق',aboutTitle:'ترابط يجعل الصيانة أسهل',
  aboutIntro:'تطور شركة Anhui LinkedTi Intelligent Technology Co., Ltd. ‏(安徽交泰智能技术有限公司) الأجهزة والبرامج وخوارزميات التشخيص للصيانة الذكية للمعدات الصناعية. نعمل مع مشغلي المصانع وشركاء التكامل ومصنّعي المعدات.',
  storyTitle:'قصة «交泰» واسم LinkedTi',
  story:['يعود اسم «交泰» (جياو تاي) إلى رمز «تاي» في كتاب التغيرات الصيني «إي تشينغ»، حيث يرمز تواصل السماء والأرض إلى الانسجام والازدهار. وتحمل قاعة جياو تاي في المدينة المحرمة ببكين الاسم نفسه. وهو يعبر بالنسبة إلينا عن ترابط المعدات والمعلومات والأشخاص.',
  'استُلهم اسم LinkedTi من فكرة التواصل في LinkedIn، مع تركيزنا على ترابط المعدات الصناعية. تدل كلمة Linked على الربط، بينما Ti هو الرمز الكيميائي للتيتانيوم، ويعكس طموحنا إلى الجودة والمتانة واستقرار الأداء.'],
  identityTitle:'شعار متجدد للشركة نفسها',identityText:'قمنا بتطوير شعار الشركة. قد تستمر المواد السابقة في حمل الشعار القديم؛ فكلا الشعارين يمثلان الشركة نفسها، 安徽交泰智能技术有限公司، والعلامة LinkedTi. يعكس التصميم الجديد استمرارية هويتنا.',oldLogo:'الشعار السابق',newLogo:'الشعار الحالي',
  contactTitle:'من أين تبدأ؟',contactText:'أجب عن اثني عشر سؤالًا اختياريًا حول قيمة المعدات وأثر التوقف والبيانات والفريق. يمكنك الاطلاع على النتيجة قبل ترك وسيلة للتواصل.',
  address:'المبنى R، هونغباوشي، منطقة التكنولوجيا المتقدمة، خفي، آنهوي، الصين',footer:'مراقبة الحالة · التشخيص · الصيانة التنبؤية',home:'الرئيسية'
 }
};
