'use client';
import {useEffect} from 'react';
import {ArrowUpRight,Activity,Network,Cpu,Workflow} from 'lucide-react';
import {Mark,Wordmark,type PageKey} from './site';
import LanguageSwitcher,{languagePath} from './languages';
import {internationalContent} from './international-content';
import './international.css';

export default function InternationalSite({page,lang}:{page:PageKey;lang:'de'|'ar'}) {
 const c=internationalContent[lang],rtl=lang==='ar';
 const href=(p='home')=>languagePath(lang,p);
 const nav=['products','applications','about'];
 const icons=[Activity,Network,Cpu,Workflow];
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=rtl?'rtl':'ltr';},[lang,rtl]);
 const products=(detail=false)=><div className="product-grid">{c.products.map(([name,title,desc,extra],i)=>{const Icon=icons[i];return <article className="product-card" key={name} id={name.toLowerCase()}><div className="product-top"><Icon size={25}/><span>0{i+1}</span></div><h3><bdi>{name}</bdi></h3><h4>{title}</h4><p>{desc}</p>{detail&&<p>{extra}</p>}</article>;})}</div>;
 const integration=<section className="section wrap intl-integration"><div className="section-heading"><div><p className="eyebrow">PLC / DCS</p><h2>{c.integrationTitle}</h2></div><p>{c.integrationIntro}</p></div><div className="intl-three">{c.integrations.map(([title,text])=><article key={title}><Network/><h3><bdi>{title}</bdi></h3><p>{text}</p></article>)}</div></section>;
 const workflow=<section className="section wrap"><div className="section-heading"><h2>{c.workflowTitle}</h2><p>{c.workflowText}</p></div><ol className="intl-workflow">{c.workflow.map((s,i)=><li key={s}><span>0{i+1}</span>{s}</li>)}</ol></section>;
 const steel=<article className="intl-case"><p className="eyebrow">{c.actual}</p><h2>{c.steelTitle}</h2><p>{c.steel}</p><small>{c.steelNote}</small></article>;
 return <div className="international-site" lang={lang} dir={rtl?'rtl':'ltr'}>
 <a href="#main" className="skip-link">{c.skip}</a>
 <header className="site-header"><div className="header-inner"><a className="brand" dir="ltr" href={href()} aria-label={c.home}><Mark/><Wordmark/></a><nav className="desktop-nav" aria-label={c.home}>{nav.map((p,i)=><a href={href(p)} key={p} aria-current={page===p?'page':undefined}>{c.nav[i]}</a>)}</nav><div className="header-actions"><LanguageSwitcher lang={lang} page={page}/><a className="header-cta" href={href('contact')}>{c.talk}<ArrowUpRight size={17}/></a></div></div><nav className="mobile-nav" aria-label={c.home}>{nav.map((p,i)=><a key={p} href={href(p)} aria-current={page===p?'page':undefined}>{c.nav[i]}</a>)}</nav></header>
 <main id="main">
 {page==='home'&&<><section className="hero wrap"><div className="hero-copy"><p className="eyebrow">{c.eyebrow}</p><h1 className="brand-promise">{c.promise[0]}<br/><em>{c.promise[1]}</em></h1><p>{c.intro}</p><div className="actions"><a className="button primary" href={href('contact')}>{c.talk}<ArrowUpRight size={19}/></a><a className="button secondary" href={href('products')}>{c.explore}</a></div></div><div className="intl-visual" aria-label={c.productsTitle}><div className="intl-visual-brand" dir="ltr"><Mark/><Wordmark/></div>{c.products.map(([name,title],i)=>{const Icon=icons[i];return <div className="intl-node" key={name}><Icon/><div><bdi>{name}</bdi><span>{title}</span></div><span className="signal-dot"/></div>;})}<div className="intl-visual-base" dir="ltr">PLC · DCS · PLCnext</div></div></section><section className="section wrap"><div className="section-heading"><h2>{c.productsTitle}</h2><p>{c.productsIntro}</p></div>{products()}</section>{integration}{workflow}<section className="section wrap">{steel}</section></>}
 {page==='products'&&<><section className="page-intro wrap"><p className="eyebrow">{c.nav[0]}</p><h1>{c.productsTitle}</h1><p className="intro-body">{c.productsIntro}</p></section><section className="section wrap">{products(true)}</section>{integration}<section className="section wrap"><div className="section-heading"><h2>{c.softwareTitle}</h2><p>{c.softwareText}</p></div><div className="intl-screens">{['euda-overview.png','euda-workspace.png'].map((image,i)=><img key={image} src={'/images/'+image} alt={`${i===0?'Euda — ': 'Euda — '}${c.softwareTitle}`} width={1267} height={576} loading="lazy"/>)}</div><p className="intl-note">{c.softwareNote}</p></section>{workflow}</>}
 {page==='applications'&&<><section className="page-intro wrap"><p className="eyebrow">{c.nav[1]}</p><h1>{c.applicationsTitle}</h1><p className="intro-body">{c.applicationsIntro}</p></section><section className="section wrap">{steel}<div className="intl-industries">{c.industries.map(([title,sub,text])=><article key={title}><p className="eyebrow">{c.exampleLabel}</p><h2>{title}</h2><h3>{sub}</h3><p>{text}</p></article>)}</div></section></>}
 {page==='about'&&<><section className="page-intro wrap"><p className="eyebrow">{c.nav[2]}</p><h1>{c.aboutTitle}</h1><p className="intro-body">{c.aboutIntro}</p></section><section className="section wrap intl-story"><h2>{c.storyTitle}</h2>{c.story.map(p=><p key={p}>{p}</p>)}</section><section className="section wrap"><div className="section-heading"><h2>{c.identityTitle}</h2><p>{c.identityText}</p></div><div className="intl-identity"><figure><div><img src="/brand/original.png" width={280} height={140} alt={c.oldLogo} loading="lazy"/></div><figcaption>{c.oldLogo}</figcaption></figure><figure><div className="brand" dir="ltr"><Mark/><Wordmark/></div><figcaption>{c.newLogo}</figcaption></figure></div></section>{integration}</>}
 <section className="contact-band wrap"><div><p className="eyebrow">LinkedTi</p><h2>{c.contactTitle}</h2><p>{c.contactText}</p></div><a className="button primary" href={href('contact')}>{c.talk}<ArrowUpRight size={19}/></a></section>
 </main><footer className="wrap"><div className="footer-top"><a href={href()} className="brand" dir="ltr"><Mark/><Wordmark/></a><p>{c.footer}</p><div><a href="mailto:sales@linkedti.com" dir="ltr">sales@linkedti.com</a><br/><a href="tel:+8613951419340" dir="ltr">+86 139 5141 9340</a><p>{c.address}</p></div></div><div className="footer-bottom"><span>© LinkedTi · 安徽交泰智能技术有限公司</span><a href="https://beian.miit.gov.cn/" target="_blank" rel="noreferrer">皖ICP备2023008887号-2</a></div></footer></div>;
}
