import type { SiteLang } from './language-path';

type RuleContent = {
  eyebrow: string; title: string; intro: string; link: string;
  cards: [string, string][];
  detailTitle: string; detailIntro: string; deliverables: [string, string][];
  commercial: string; scope: string; download: string;
  workflowTitle: string; workflowIntro: string; steps: string[];
  exampleTitle: string; example: string; exampleNote: string;
  aboutTitle: string; about: string;
};

export const ruleContent: Record<SiteLang, RuleContent> = {
  zh: {
    eyebrow: '设备诊断知识与规则包',
    title: '把设备经验，变成可执行、可复用的诊断能力。',
    intro: '数据告诉我们设备发生了什么；设备机理和诊断规则，帮助判断为什么发生、下一步该做什么。交泰智能将现场经验沉淀为可配置的规则与模板，让诊断能力融入现有运维流程。',
    link: '了解诊断规则与交付内容',
    cards: [
      ['从机理出发', '结合设备结构、工况与故障特征，定义需要关注的信号和判断条件。'],
      ['让经验可以执行', '通过可视化编排、参数配置与规则部署，把判断逻辑用于持续监测；模板支持保存、分类与复用。'],
      ['在现场持续完善', '将诊断建议与现场复核、维护结果相互印证，为下一次判断积累依据。'],
    ],
    detailTitle: '软件之外，还有可以积累的运维知识。',
    detailIntro: '设备诊断知识与规则包是 Euda 分析诊断能力的交付内容，可结合项目配置。规则说明适用条件，算法提供分析依据，Agent 辅助信息整理与流程协同，现场人员确认结果。',
    deliverables: [
      ['设备与工况知识', '明确设备对象、测点、信号来源、运行工况和故障特征，建立诊断的适用边界。'],
      ['规则与参数模板', '配置判断条件、算法参数、告警输出及数据源绑定；支持图形化编排、部署与模板复用。'],
      ['诊断与处置建议', '结合趋势、频谱等分析结果，形成可供复核的故障线索与维护建议。'],
      ['现场适配与更新', '结合现场工况调整参数，通过检修反馈完善规则与知识；更新范围随项目约定。'],
    ],
    commercial: '交付可以按“基础软件能力 + 设备诊断规则包 + 现场适配与持续更新服务”组合，具体设备范围、验证条件与服务内容在项目中明确。',
    scope: '规则与模型需结合实际设备、测点及工况验证。Agent 辅助闭环协同；设备控制由 PLC / DCS 和经配置的本地逻辑执行。',
    download: '下载交泰智能宣传册（中文 PDF）',
    workflowTitle: '从发现异常，到经验沉淀。',
    workflowIntro: '把一次诊断接到后续行动上，让每次现场确认都能为下一次维护提供依据。',
    steps: ['设备数据', '规则判断与算法分析', '诊断建议', '现场复核', '维护处理', '效果确认与知识沉淀'],
    exampleTitle: '一处轴承损伤，带来一条可积累的诊断经验。',
    example: '在轧机辊道项目中，系统先发现振动异常，再分析劣化趋势与轴承故障线索。设备外观和常规巡检尚未发现明显异常，后续检修拆解确认了滚珠损伤，并及时更换轴承。这样的“信号—判断—复核”记录，为后续同类设备的规则适配提供依据。',
    exampleNote: '真实项目经验；本次案例未使用 Agent。案例说明诊断与现场验证的价值，不代表可不经适配直接用于所有设备。',
    aboutTitle: '连接设备，也连接经验与行动。',
    about: '交泰智能提供传感器、网关、软件与诊断算法，也把设备知识和现场经验沉淀为可配置、可复用的规则。通过与自动化系统融合、与现场人员协作，让设备健康数据进入维护闭环，逐步积累属于客户的运维知识资产。',
  },
  en: {
    eyebrow: 'Equipment diagnostic knowledge & rule packages',
    title: 'Turn equipment experience into repeatable diagnostic capability.',
    intro: 'Data shows what is happening. Equipment physics and diagnostic rules help explain why, and what to check next. LinkedTi turns field experience into configurable rules and templates that fit existing maintenance workflows.',
    link: 'Explore diagnostic rules and deliverables',
    cards: [
      ['Grounded in equipment physics', 'Equipment structure, operating conditions and failure signatures define the signals and conditions to evaluate.'],
      ['Make experience executable', 'Visual configuration, parameters and deployed rules support continuous monitoring. Templates can be saved, classified and reused.'],
      ['Refine through field feedback', 'Cross-check diagnostic recommendations against inspections and maintenance outcomes to inform future decisions.'],
    ],
    detailTitle: 'Software capabilities, backed by reusable maintenance knowledge.',
    detailIntro: 'Diagnostic knowledge and rule packages form part of Euda’s analysis and diagnostic deliverables, configured for each project. Rules define conditions, algorithms supply evidence, and Agent assists information handling and workflow coordination. People verify the outcome.',
    deliverables: [
      ['Equipment and operating context', 'Define the equipment, measurement points, signals, operating conditions and failure signatures that bound the diagnosis.'],
      ['Rules and parameter templates', 'Configure conditions, algorithm parameters, alarm outputs and data sources; visually compose, deploy and reuse templates.'],
      ['Diagnostic and maintenance guidance', 'Use trends, spectra and other analysis to produce fault indications and maintenance recommendations for verification.'],
      ['Field adaptation and updates', 'Tune parameters to actual conditions and refine knowledge using maintenance feedback. Update scope is agreed for the project.'],
    ],
    commercial: 'Delivery can combine core software capabilities, equipment diagnostic rule packages, and field adaptation with ongoing updates. Equipment coverage, validation conditions and service scope are defined for each project.',
    scope: 'Rules and models require validation for the actual equipment, measurement points and conditions. Agent supports workflow coordination. PLC / DCS systems and configured local logic execute equipment control.',
    download: 'Download the LinkedTi brochure (Chinese PDF)',
    workflowTitle: 'From an abnormal signal to reusable experience.',
    workflowIntro: 'Connect diagnostic findings to action, and let each field confirmation inform the next maintenance decision.',
    steps: ['Equipment data', 'Rules & algorithm analysis', 'Diagnostic guidance', 'Field verification', 'Maintenance action', 'Outcome review & knowledge capture'],
    exampleTitle: 'A bearing fault becomes an experience worth retaining.',
    example: 'In a rolling-mill roller conveyor project, vibration monitoring revealed an anomaly and analysis identified deterioration and a potential bearing fault. Appearance and routine inspections showed no obvious problem. Disassembly during a scheduled maintenance window confirmed damaged bearing balls, and the bearing was replaced. Recording the signal, diagnosis and verification provides evidence for adapting rules to similar equipment.',
    exampleNote: 'Actual project experience; Agent was not used in this case. The case illustrates diagnostics and field validation, rather than a universally deployable rule package.',
    aboutTitle: 'Connect equipment, experience and action.',
    about: 'Alongside sensors, gateways, software and diagnostic algorithms, LinkedTi captures equipment knowledge and field experience in configurable, reusable rules. Automation integration and collaboration with field teams connect equipment health data to maintenance workflows and progressively build the customer’s maintenance knowledge assets.',
  },
  ja: {
    eyebrow: '設備診断ナレッジとルールパッケージ',
    title: '設備の経験を、実行・再利用できる診断能力へ。',
    intro: 'データは設備で何が起きているかを示します。設備の物理的な仕組みと診断ルールは、その原因と次に確認すべきことを考える手掛かりになります。LinkedTi は現場の経験を設定可能なルールとテンプレートに整理し、既存の保全業務につなげます。',
    link: '診断ルールと提供内容を見る',
    cards: [
      ['設備の仕組みに基づく', '設備構造、運転条件、故障特性を踏まえ、監視する信号と判定条件を定義します。'],
      ['経験を実行できる形に', '視覚的なルール編集、パラメーター設定、ルールの展開により継続監視を支援。テンプレートの保存・分類・再利用にも対応します。'],
      ['現場の結果で改善する', '診断提案を現場確認や保全結果と照合し、次の判断に役立つ知識を蓄積します。'],
    ],
    detailTitle: 'ソフトウェアとともに、保全の知識を蓄積する。',
    detailIntro: '診断ナレッジとルールパッケージは、Euda の分析・診断機能に関連する提供内容です。プロジェクトごとに設定し、ルールが条件を定義し、アルゴリズムが分析の根拠を示します。Agent は情報整理と業務連携を支援し、現場担当者が結果を確認します。',
    deliverables: [
      ['設備と運転条件の知識', '対象設備、測定点、信号、運転条件、故障特性を整理し、診断の適用範囲を明確にします。'],
      ['ルールとパラメーターテンプレート', '判定条件、分析パラメーター、警報出力、データソースを設定。視覚的な編集・展開・テンプレート再利用に対応します。'],
      ['診断と保全の提案', 'トレンドや周波数分析などに基づき、確認すべき故障の兆候と保全の提案を提示します。'],
      ['現場適合と更新', '実際の運転条件に合わせて調整し、保全結果をルールと知識に反映します。更新範囲は案件ごとに合意します。'],
    ],
    commercial: '基本ソフトウェア機能、設備診断ルールパッケージ、現場適合・継続更新サービスを組み合わせて提供できます。対象設備、検証条件、サービス範囲は案件ごとに定めます。',
    scope: 'ルールとモデルは実際の設備・測定点・運転条件での検証が必要です。Agent は業務連携を支援し、設備制御は PLC / DCS と設定されたローカルロジックが実行します。',
    download: 'LinkedTi 会社案内をダウンロード（中国語 PDF）',
    workflowTitle: '異常の発見から、経験の蓄積へ。',
    workflowIntro: '診断をその後の行動につなぎ、現場での確認結果を次の保全判断に役立てます。',
    steps: ['設備データ', 'ルール判定・アルゴリズム分析', '診断提案', '現場確認', '保全作業', '効果確認・知識蓄積'],
    exampleTitle: '軸受の損傷から、次につながる診断経験へ。',
    example: '圧延設備のローラーテーブルでは、振動の異常を検出し、劣化傾向と軸受の故障兆候を分析しました。外観や通常点検では明確な異常が見られませんでしたが、定期修理時の分解で転動体の損傷が確認され、軸受を交換しました。信号・判断・確認結果の記録は、同種設備のルール適合に役立ちます。',
    exampleNote: '実際のプロジェクト事例です。この事例では Agent を使用していません。診断と現場検証の価値を示すもので、すべての設備に無調整で適用できることを意味しません。',
    aboutTitle: '設備と、経験と、行動をつなぐ。',
    about: 'LinkedTi はセンサー、ゲートウェイ、ソフトウェア、診断アルゴリズムに加え、設備の知識と現場経験を設定・再利用できるルールに整理します。自動化システムとの統合と現場担当者との協働を通じ、設備の健全性データを保全業務につなぎ、お客様の保全知識資産を蓄積します。',
  },
  de: {
    eyebrow: 'Diagnosewissen und Regelpakete für Anlagen',
    title: 'Anlagenerfahrung in ausführbare, wiederverwendbare Diagnose überführen.',
    intro: 'Daten zeigen, was in einer Anlage passiert. Physikalisches Anlagenwissen und Diagnoseregeln helfen, Ursachen und nächste Prüfschritte einzuordnen. LinkedTi überführt Praxiserfahrung in konfigurierbare Regeln und Vorlagen für bestehende Instandhaltungsabläufe.',
    link: 'Diagnoseregeln und Leistungsumfang kennenlernen',
    cards: [
      ['Auf Anlagenwissen aufbauen', 'Anlagenstruktur, Betriebsbedingungen und Fehlermerkmale bestimmen relevante Signale und Bewertungskriterien.'],
      ['Erfahrung ausführbar machen', 'Visuelle Konfiguration, Parameter und bereitgestellte Regeln unterstützen die kontinuierliche Überwachung. Vorlagen lassen sich speichern, kategorisieren und wiederverwenden.'],
      ['Durch Rückmeldungen verbessern', 'Diagnoseempfehlungen werden mit Vor-Ort-Prüfungen und Wartungsergebnissen abgeglichen, um spätere Entscheidungen zu unterstützen.'],
    ],
    detailTitle: 'Software mit wiederverwendbarem Instandhaltungswissen.',
    detailIntro: 'Diagnosewissen und Regelpakete gehören zum projektbezogenen Leistungsumfang der Analyse und Diagnose mit Euda. Regeln definieren Bedingungen, Algorithmen liefern Anhaltspunkte und Agent unterstützt Informationsaufbereitung und Abläufe. Das Ergebnis wird durch Menschen bestätigt.',
    deliverables: [
      ['Anlagen- und Betriebswissen', 'Anlagen, Messpunkte, Signale, Betriebsbedingungen und Fehlermerkmale festlegen, um den Anwendungsbereich der Diagnose zu bestimmen.'],
      ['Regeln und Parametervorlagen', 'Bedingungen, Analyseparameter, Alarmausgaben und Datenquellen konfigurieren; Regeln visuell erstellen, bereitstellen und Vorlagen wiederverwenden.'],
      ['Diagnose- und Handlungsempfehlungen', 'Trends, Spektren und weitere Analysen liefern Hinweise auf Fehler und Empfehlungen zur Prüfung und Instandhaltung.'],
      ['Anpassung und Aktualisierung', 'Parameter an reale Bedingungen anpassen und Wissen mit Wartungsrückmeldungen verbessern. Der Umfang der Aktualisierung wird projektbezogen vereinbart.'],
    ],
    commercial: 'Die Bereitstellung kann Kernfunktionen der Software, anlagenspezifische Diagnoseregelpakete sowie Anpassung und laufende Aktualisierung kombinieren. Anlagenumfang, Validierungsbedingungen und Leistungen werden je Projekt definiert.',
    scope: 'Regeln und Modelle müssen für die tatsächlichen Anlagen, Messpunkte und Betriebsbedingungen validiert werden. Agent unterstützt Abläufe. PLC / DCS und konfigurierte lokale Logik führen die Anlagensteuerung aus.',
    download: 'LinkedTi-Broschüre herunterladen (PDF auf Chinesisch)',
    workflowTitle: 'Vom auffälligen Signal zum nutzbaren Erfahrungswissen.',
    workflowIntro: 'Diagnose und Handlung verbinden: Jede Bestätigung vor Ort liefert Anhaltspunkte für die nächste Instandhaltungsentscheidung.',
    steps: ['Anlagendaten', 'Regeln und Algorithmusanalyse', 'Diagnoseempfehlung', 'Prüfung vor Ort', 'Instandhaltung', 'Ergebnisprüfung und Wissensaufbau'],
    exampleTitle: 'Ein Lagerschaden wird zu wertvollem Diagnosewissen.',
    example: 'In einem Rollgangprojekt eines Walzwerks zeigten Schwingungsdaten eine Auffälligkeit. Die Analyse deutete auf Verschlechterung und einen möglichen Lagerschaden hin. Sichtkontrolle und Routineinspektion zeigten noch kein eindeutiges Problem. Bei der Demontage während einer geplanten Wartung wurden beschädigte Lagerkugeln bestätigt und das Lager ersetzt. Die dokumentierten Signale, Bewertungen und Prüfergebnisse unterstützen die Regelanpassung für ähnliche Anlagen.',
    exampleNote: 'Reales Projekt; Agent wurde hier nicht eingesetzt. Das Beispiel zeigt Diagnose und Validierung vor Ort, kein universell ohne Anpassung einsetzbares Regelpaket.',
    aboutTitle: 'Anlagen, Erfahrung und Handlung verbinden.',
    about: 'Neben Sensoren, Gateways, Software und Diagnosealgorithmen überführt LinkedTi Anlagenwissen und Praxiserfahrung in konfigurierbare, wiederverwendbare Regeln. Die Integration in Automatisierungssysteme und die Zusammenarbeit mit Teams vor Ort verbinden Zustandsdaten mit der Instandhaltung und bauen schrittweise Wissenswerte für Kunden auf.',
  },
  ar: {
    eyebrow: 'المعرفة التشخيصية للمعدات وحزم القواعد',
    title: 'تحويل خبرة المعدات إلى قدرات تشخيص قابلة للتنفيذ وإعادة الاستخدام.',
    intro: 'تُظهر البيانات ما يحدث في المعدات، وتساعد المعرفة بآلياتها وقواعد التشخيص على فهم السبب وتحديد ما ينبغي فحصه بعد ذلك. تحوّل LinkedTi الخبرة الميدانية إلى قواعد وقوالب قابلة للتهيئة تتكامل مع إجراءات الصيانة القائمة.',
    link: 'استكشف قواعد التشخيص ومحتويات التسليم',
    cards: [
      ['الاستناد إلى آليات المعدات', 'تحدد بنية المعدات وظروف التشغيل وخصائص الأعطال الإشارات المهمة وشروط التقييم.'],
      ['جعل الخبرة قابلة للتنفيذ', 'يدعم التحرير المرئي وإعداد المعلمات ونشر القواعد المراقبة المستمرة، مع حفظ القوالب وتصنيفها وإعادة استخدامها.'],
      ['التحسين بنتائج الميدان', 'تُراجع التوصيات التشخيصية في ضوء الفحص الميداني ونتائج الصيانة لتوفير أساس أفضل للقرارات اللاحقة.'],
    ],
    detailTitle: 'برمجيات تدعمها معرفة صيانة قابلة لإعادة الاستخدام.',
    detailIntro: 'تندرج المعرفة التشخيصية وحزم القواعد ضمن مخرجات التحليل والتشخيص في Euda، وتُهيّأ وفق كل مشروع. تحدد القواعد الشروط، وتوفر الخوارزميات الأدلة، ويساعد Agent في تنظيم المعلومات وتنسيق العمل. ويتحقق فريق الموقع من النتائج.',
    deliverables: [
      ['معرفة المعدات وظروف التشغيل', 'تحديد المعدات ونقاط القياس والإشارات وظروف التشغيل وخصائص الأعطال لتوضيح نطاق تطبيق التشخيص.'],
      ['القواعد وقوالب المعلمات', 'تهيئة شروط التقييم ومعلمات التحليل ومخرجات الإنذار ومصادر البيانات، مع التحرير المرئي والنشر وإعادة استخدام القوالب.'],
      ['التشخيص وتوصيات الصيانة', 'استخدام الاتجاهات والأطياف والتحليلات الأخرى لتقديم مؤشرات أعطال وتوصيات صيانة قابلة للتحقق.'],
      ['التكييف الميداني والتحديث', 'ضبط المعلمات وفق الظروف الفعلية وتحسين المعرفة بنتائج الصيانة. يُتفق على نطاق التحديث في المشروع.'],
    ],
    commercial: 'يمكن الجمع بين وظائف البرمجيات الأساسية وحزم قواعد تشخيص المعدات وخدمات التكييف الميداني والتحديث المستمر. ويُحدد نطاق المعدات وشروط التحقق والخدمات لكل مشروع.',
    scope: 'تحتاج القواعد والنماذج إلى التحقق على المعدات ونقاط القياس وظروف التشغيل الفعلية. يدعم Agent تنسيق العمل، بينما تنفذ أنظمة PLC / DCS والمنطق المحلي المهيّأ التحكم في المعدات.',
    download: 'تنزيل كتيب LinkedTi (ملف PDF باللغة الصينية)',
    workflowTitle: 'من الإشارة غير الطبيعية إلى خبرة قابلة للاستفادة.',
    workflowIntro: 'ربط نتائج التشخيص بالإجراءات التالية، كي يسهم كل تحقق ميداني في قرار الصيانة المقبل.',
    steps: ['بيانات المعدات', 'تقييم القواعد وتحليل الخوارزميات', 'التوصيات التشخيصية', 'التحقق الميداني', 'إجراءات الصيانة', 'تأكيد النتائج وتوثيق المعرفة'],
    exampleTitle: 'تلف محمل يتحول إلى خبرة تشخيصية تستحق الاحتفاظ.',
    example: 'في مشروع ناقل بكرات بمصنع درفلة، كشفت مراقبة الاهتزازات عن حالة غير طبيعية، وأشار التحليل إلى تدهور واحتمال تلف محمل. لم يُظهر المظهر الخارجي والفحص الدوري مشكلة واضحة. وأكد التفكيك خلال صيانة مقررة وجود تلف في كرات المحمل، ثم جرى استبداله. يوفر توثيق الإشارة والتشخيص والتحقق أساساً لتكييف القواعد مع معدات مماثلة.',
    exampleNote: 'خبرة من مشروع فعلي؛ لم يُستخدم Agent في هذه الحالة. توضح الحالة قيمة التشخيص والتحقق الميداني، ولا تعني أن الحزمة قابلة للتطبيق على جميع المعدات دون تكييف.',
    aboutTitle: 'ربط المعدات والخبرة والعمل.',
    about: 'إلى جانب المستشعرات والبوابات والبرمجيات وخوارزميات التشخيص، تصوغ LinkedTi معرفة المعدات والخبرة الميدانية في قواعد قابلة للتهيئة وإعادة الاستخدام. ومن خلال التكامل مع أنظمة الأتمتة والتعاون مع فرق الموقع، تربط بيانات صحة المعدات بإجراءات الصيانة وتبني تدريجياً الأصول المعرفية الخاصة بالعميل.',
  },
};
